homepage: "https://git.gnunet.org/libmicrohttpd2.git"
main_repo: "https://git.gnunet.org/libmicrohttpd2.git"
primary_contact: "arthur.chan@adalogics.com"
vendor_ccs:
  - "david@adalogics.com"
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
